// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementSystem.Context;

#nullable disable

namespace UserManagementSystem.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220806110920_NewUsersCreated")]
    partial class NewUsersCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("493c3228-3444-4a49-9cc0-e8532edc59b2"),
                            Email = "jwaitz@rambler.ru",
                            FirstName = "Josh",
                            LastName = "Waitzkin",
                            Password = "xf0JYDbALF",
                            Status = "active",
                            Username = "jwaitz"
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Email = "call@yolasite.com",
                            FirstName = "Cal",
                            LastName = " Newport",
                            Password = "DOIm5h",
                            Status = "active",
                            Username = "cal"
                        },
                        new
                        {
                            Id = new Guid("494c3228-3444-4a49-9cc0-e8532edc59b2"),
                            Email = "cnussgen2@tmall.com",
                            FirstName = "Roger",
                            LastName = "Velichkovic",
                            Password = "v05mT7Xz4",
                            Status = "inactive",
                            Username = "veli099"
                        },
                        new
                        {
                            Id = new Guid("d3e757a9-5850-4625-abb8-c69aed20ffbe"),
                            Email = "cnussgen2@tmall.com",
                            FirstName = "Felipe",
                            LastName = "Verna",
                            Password = "v05mT7Xz43",
                            Status = "inactive",
                            Username = "verna"
                        },
                        new
                        {
                            Id = new Guid("79ac0db0-d44c-4c06-94ac-2d130b193542"),
                            Email = "warnall@tmall.com",
                            FirstName = "Keelby",
                            LastName = " Warnals",
                            Password = "v05dasdmT7Xz43",
                            Status = "active",
                            Username = "wwyord"
                        },
                        new
                        {
                            Id = new Guid("7cfa6f3f-2384-467c-b802-ea0188a375fd"),
                            Email = "connnorwannabe@tmall.com",
                            FirstName = "Connor",
                            LastName = "Cockerill",
                            Password = "8VSTlTbA",
                            Status = "active",
                            Username = "wwyord"
                        },
                        new
                        {
                            Id = new Guid("e502b86f-542a-4cc7-ba23-218d1ff622e5"),
                            Email = "cast@tmall.com",
                            FirstName = "Sterling",
                            LastName = "Castelli",
                            Password = "ssssterling32312321",
                            Status = "active",
                            Username = "ssssterling"
                        },
                        new
                        {
                            Id = new Guid("f5891e36-4d39-4da3-82d5-2f02bb156cdd"),
                            Email = "ag342@tmall.com",
                            FirstName = "Ailsun",
                            LastName = " Agutter",
                            Password = "123456",
                            Status = "active",
                            Username = "ag342"
                        },
                        new
                        {
                            Id = new Guid("4dd40884-e54b-41bb-93a7-13e35710debc"),
                            Email = "bobby76@tmall.com",
                            FirstName = "Bob",
                            LastName = "Baalham",
                            Password = "O2kIiMy7",
                            Status = "active",
                            Username = "bobby76"
                        },
                        new
                        {
                            Id = new Guid("187f09fe-847f-4167-8798-fb6b646f1712"),
                            Email = "willdewill@tmall.com",
                            FirstName = "Will",
                            LastName = "Wimsett",
                            Password = "ZG7AZi",
                            Status = "active",
                            Username = "willdewill"
                        },
                        new
                        {
                            Id = new Guid("e3852ef6-1655-4f43-b3cd-79d6616552ff"),
                            Email = "biaggi23@tmall.com",
                            FirstName = "Saraann",
                            LastName = " De Biaggi",
                            Password = "m80JXxgWb",
                            Status = "active",
                            Username = "Biaggi23"
                        },
                        new
                        {
                            Id = new Guid("fe132df5-8293-48e8-8fc6-79b79332e2c4"),
                            Email = "maren@tmall.com",
                            FirstName = "Maren",
                            LastName = "MacConchie",
                            Password = "XFtOsOHaeF",
                            Status = "inactive",
                            Username = "MacConchie34"
                        },
                        new
                        {
                            Id = new Guid("374793ec-aeae-4013-8b72-6c48690286af"),
                            Email = "savinas@tmall.com",
                            FirstName = "Savina",
                            LastName = " Spriddle",
                            Password = "9y3m9I",
                            Status = "inactive",
                            Username = "savinas"
                        },
                        new
                        {
                            Id = new Guid("198139bf-de0f-4c78-9a45-ec66df49413c"),
                            Email = "hillhed@tmall.com",
                            FirstName = "Hedwiga",
                            LastName = "Hillatt",
                            Password = "ued8qu4Y",
                            Status = "active",
                            Username = "hillhed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
